-- ps5rs NID catalog import for Supabase
--
-- Usage:
--   1. Edit paths below to match your CSV locations
--   2. psql -h <host> -U <user> -d <db> -f seed.sql
--
-- CSVs generated by: cd tools/seed-supabase && cargo run --release

-- Create the nid_names table (safe to run multiple times)
CREATE TABLE IF NOT EXISTS public.nid_names (
  id bigint generated always as identity not null,
  nid text not null,
  name text not null,
  library text null,
  source text not null default 'community'::text,
  confidence smallint not null default 0,
  evidence jsonb null,
  created_at timestamp with time zone not null default now(),
  constraint nid_names_pkey primary key (id),
  constraint nid_names_nid_name_library_key unique (nid, name, library),
  constraint nid_names_confidence_check check (
    ((confidence >= 0) and (confidence <= 100))
  )
);

CREATE INDEX IF NOT EXISTS nid_names_name_idx ON public.nid_names USING btree (name);
CREATE INDEX IF NOT EXISTS nid_names_library_idx ON public.nid_names USING btree (library);

-- Stage 1: Import nid_entries (canonical NID → u64 mapping)
-- Uncomment if you have a nid_entries table:
-- CREATE TABLE IF NOT EXISTS public.nid_entries (
--   nid text primary key,
--   nid_u64 bigint not null,
--   primary_name text not null
-- );
-- \copy public.nid_entries (nid, nid_u64, primary_name)
--   FROM 'output/nid_entries.csv'
--   WITH (FORMAT csv, HEADER true, NULL '')
-- ON CONFLICT (nid) DO NOTHING;

-- Stage 2: Import nid_names
-- Empty fields in CSV are imported as NULL.
-- Duplicate (nid, name, library) rows are skipped.
\copy public.nid_names (nid, name, library, source, confidence, evidence)
  FROM 'output/nid_names.csv'
  WITH (FORMAT csv, HEADER true, NULL '')
ON CONFLICT (nid, name, library) DO NOTHING;

-- Stage 3: catalog_export view (stable public API for ps5rs catalog sync)
-- All columns are guaranteed non-null; the client deserializes plain strings.
CREATE OR REPLACE VIEW public.catalog_export AS
SELECT
    nid,
    name,
    COALESCE(library, '') AS library,
    COALESCE(tag, '') AS tag,
    COALESCE(source, '') AS source
FROM (
    SELECT
        nid,
        name,
        library,
        NULL::text AS tag,
        source
    FROM public.nid_names
) t
ORDER BY library, name;

-- Verify import
SELECT COUNT(*) AS nid_names_count FROM public.nid_names;
SELECT COUNT(DISTINCT nid) AS unique_nids FROM public.nid_names;
