[package]
name = "ps5-elf"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "ELF64 binary format parser (zero-copy)"

[dependencies]
ps5-format = { path = "../ps5-format" }
ps5-nid = { path = "../ps5-nid" }

[dev-dependencies]
proptest = "1"

[lints]
workspace = true
