use crate::functions::{FunctionSignature, Provenance};
use crate::types::AbiType;

pub fn seed_signatures() -> Vec<FunctionSignature> {
    vec![
        FunctionSignature {
            name: "sceKernelSleep".to_string(),
            return_type: AbiType::I32,
            params: vec![AbiType::U32],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "sceKernelUsleep".to_string(),
            return_type: AbiType::I32,
            params: vec![AbiType::U32],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "sceKernelGetProcessTime".to_string(),
            return_type: AbiType::U64,
            params: vec![],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "sceKernelGetProcessTimeCounter".to_string(),
            return_type: AbiType::U64,
            params: vec![],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "scePthreadCreate".to_string(),
            return_type: AbiType::I32,
            params: vec![AbiType::Ptr, AbiType::Ptr, AbiType::Ptr, AbiType::Ptr],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "scePthreadJoin".to_string(),
            return_type: AbiType::I32,
            params: vec![AbiType::Ptr, AbiType::Ptr],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "scePthreadMutexInit".to_string(),
            return_type: AbiType::I32,
            params: vec![AbiType::Ptr, AbiType::Ptr],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "scePthreadMutexLock".to_string(),
            return_type: AbiType::I32,
            params: vec![AbiType::Ptr],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "scePthreadMutexUnlock".to_string(),
            return_type: AbiType::I32,
            params: vec![AbiType::Ptr],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "scePthreadCondInit".to_string(),
            return_type: AbiType::I32,
            params: vec![AbiType::Ptr, AbiType::Ptr],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "scePthreadCondWait".to_string(),
            return_type: AbiType::I32,
            params: vec![AbiType::Ptr, AbiType::Ptr],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "scePthreadCondSignal".to_string(),
            return_type: AbiType::I32,
            params: vec![AbiType::Ptr],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "malloc".to_string(),
            return_type: AbiType::Ptr,
            params: vec![AbiType::U64],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "free".to_string(),
            return_type: AbiType::Void,
            params: vec![AbiType::Ptr],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "memcpy".to_string(),
            return_type: AbiType::Ptr,
            params: vec![AbiType::Ptr, AbiType::Ptr, AbiType::U64],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "memset".to_string(),
            return_type: AbiType::Ptr,
            params: vec![AbiType::Ptr, AbiType::I32, AbiType::U64],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "printf".to_string(),
            return_type: AbiType::I32,
            params: vec![AbiType::Ptr],
            variadic: true,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "snprintf".to_string(),
            return_type: AbiType::I32,
            params: vec![AbiType::Ptr, AbiType::U64, AbiType::Ptr],
            variadic: true,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "puts".to_string(),
            return_type: AbiType::I32,
            params: vec![AbiType::Ptr],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "sceKernelOpen".to_string(),
            return_type: AbiType::I32,
            params: vec![AbiType::Ptr, AbiType::I32, AbiType::I32],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "sceKernelClose".to_string(),
            return_type: AbiType::I32,
            params: vec![AbiType::I32],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "sceKernelRead".to_string(),
            return_type: AbiType::I32,
            params: vec![AbiType::I32, AbiType::Ptr, AbiType::U64],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "sceKernelWrite".to_string(),
            return_type: AbiType::I32,
            params: vec![AbiType::I32, AbiType::Ptr, AbiType::U64],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "sceKernelMmap".to_string(),
            return_type: AbiType::Ptr,
            params: vec![
                AbiType::Ptr,
                AbiType::U64,
                AbiType::I32,
                AbiType::I32,
                AbiType::I32,
                AbiType::U64,
            ],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "sceKernelMunmap".to_string(),
            return_type: AbiType::I32,
            params: vec![AbiType::Ptr, AbiType::U64],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "sceVideoOutOpen".to_string(),
            return_type: AbiType::I32,
            params: vec![AbiType::I32, AbiType::I32, AbiType::I32, AbiType::Ptr],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "scePadCreate".to_string(),
            return_type: AbiType::I32,
            params: vec![AbiType::I32],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "scePadRead".to_string(),
            return_type: AbiType::I32,
            params: vec![AbiType::I32, AbiType::Ptr, AbiType::I32],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "sceAudioOutOpen".to_string(),
            return_type: AbiType::I32,
            params: vec![AbiType::I32, AbiType::I32, AbiType::I32, AbiType::I32],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "sceGnmDrawIndex".to_string(),
            return_type: AbiType::U32,
            params: vec![AbiType::Ptr, AbiType::U32, AbiType::Ptr],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "sceAgcCreate".to_string(),
            return_type: AbiType::I32,
            params: vec![AbiType::Ptr],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "sceSaveDataMount".to_string(),
            return_type: AbiType::I32,
            params: vec![AbiType::Ptr, AbiType::Ptr],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "sceHttpCreate".to_string(),
            return_type: AbiType::I32,
            params: vec![AbiType::Ptr, AbiType::I32],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "sceNetSend".to_string(),
            return_type: AbiType::I32,
            params: vec![AbiType::I32, AbiType::Ptr, AbiType::U64, AbiType::I32],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "sceRtcGetCurrentTick".to_string(),
            return_type: AbiType::I32,
            params: vec![AbiType::Ptr],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "sceRandomGetRandomNumber".to_string(),
            return_type: AbiType::I32,
            params: vec![AbiType::Ptr, AbiType::U64],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "sceDbgLoggingHandler".to_string(),
            return_type: AbiType::U32,
            params: vec![AbiType::I32, AbiType::Ptr],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "sceDbgSetMinimumLogLevel".to_string(),
            return_type: AbiType::U32,
            params: vec![AbiType::I32],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "sceKernelAllocateDirectMemory".to_string(),
            return_type: AbiType::I32,
            params: vec![
                AbiType::U64,
                AbiType::U64,
                AbiType::U64,
                AbiType::I32,
                AbiType::Ptr,
            ],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "sceKernelMapDirectMemory".to_string(),
            return_type: AbiType::I32,
            params: vec![
                AbiType::Ptr,
                AbiType::U64,
                AbiType::I32,
                AbiType::I32,
                AbiType::U64,
                AbiType::Ptr,
            ],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "exit".to_string(),
            return_type: AbiType::U32,
            params: vec![AbiType::I32],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "abort".to_string(),
            return_type: AbiType::U32,
            params: vec![],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "rand".to_string(),
            return_type: AbiType::I32,
            params: vec![],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "srand".to_string(),
            return_type: AbiType::U32,
            params: vec![AbiType::U32],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "qsort".to_string(),
            return_type: AbiType::U32,
            params: vec![AbiType::Ptr, AbiType::U64, AbiType::U64, AbiType::Ptr],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "strlen".to_string(),
            return_type: AbiType::U64,
            params: vec![AbiType::Ptr],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "strcmp".to_string(),
            return_type: AbiType::I32,
            params: vec![AbiType::Ptr, AbiType::Ptr],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "strcpy".to_string(),
            return_type: AbiType::Ptr,
            params: vec![AbiType::Ptr, AbiType::Ptr],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "fopen".to_string(),
            return_type: AbiType::Ptr,
            params: vec![AbiType::Ptr, AbiType::Ptr],
            variadic: false,
            provenance: Provenance::Unverified,
        },
        FunctionSignature {
            name: "fclose".to_string(),
            return_type: AbiType::I32,
            params: vec![AbiType::Ptr],
            variadic: false,
            provenance: Provenance::Unverified,
        },
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn seed_has_50() {
        assert_eq!(seed_signatures().len(), 50);
    }

    #[test]
    fn all_have_names() {
        for sig in seed_signatures() {
            assert!(!sig.name.is_empty());
        }
    }
}
